FROM rockylinux/rockylinux:10
SHELL ["/usr/bin/bash", "-c"]

RUN dnf install --quiet -y epel-release

RUN dnf copr enable -y @rpm-software-management/tito
RUN dnf clean all && dnf update -y

RUN dnf install --quiet -y \
    koji \
    fedpkg \
    git \
    python-xmltodict \
    rpmdevtools \
    rpm-sign \
    mock \
    ccache \
    zstd \
    createrepo \
    rpmlint \
    ShellCheck \
    pykickstart \
    lorax \
    anaconda \
    lorax-lmc-novirt \
    dracut-live \
    kiwi \
    # tito \
    xorriso \
    erofs-utils \
    qemu-img \
    kiwi-boxed-plugin \
    pip \
&& dnf clean all

RUN pip3 install --user tito
ENV PATH="/root/.local/bin:${PATH}"

COPY mock-defaults.cfg /etc/mock/site-defaults.cfg
