name: Build image 'fedora-ci'
on:
  push:
    branches:
      - main
jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: unstable ${{ github.sha }}
      branch: main
