name: Build image 'fedora-silverblue'
on:
  push:
    branches:
      - main
    paths:
      - 'fedora-silverblue/*'
jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-silverblue"
      tags: unstable
      publish: ${{ github.ref == 'refs/heads/main' }}
      branch: main
