name: Update all images
on:
  workflow_dispatch:
  schedule:
    # Every day at 2:49 AM
    - cron: "49 2 * * *"

jobs:
  fedora-ci-41:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: '41'
      publish: true
      branch: f41

  fedora-ci-42:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: "42"
      publish: true
      branch: f42

  fedora-silverblue-41:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-silverblue"
      tags: '41'
      publish: true
      branch: f41

  fedora-silverblue-42:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-silverblue"
      tags: '42'
      publish: true
      branch: f42

  fedora-ci-unstable:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: unstable
      publish: true
      branch: main

  fedora-silverblue-unstable:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-silverblue"
      tags: unstable
      publish: true
      branch: main
  cleanup-old-images:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/delete-package-versions@v5"
      with:
        package-name: fedora-ci
        package-type: container
        delete-only-untagged-versions: true
        min-versions-to-keep: 3
    - uses: "actions/delete-package-versions@v5"
      with:
        package-name: fedora-silverblue
        package-type: container
        delete-only-untagged-versions: true
        min-versions-to-keep: 3
