name: Update all images
on:
  schedule:
    # Every day at 2:49 AM
    - cron: "49 2 * * *"

jobs:
  fedora-ci-40:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: "40"
      publish: true
      branch: f40

  fedora-ci-unstable:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: unstable
      publish: true
      branch: main

  fedora-silverblue-unstable:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-silverblue"
      tags: unstable
      publish: true
      branch: main
